# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('ordered_student_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('ordered_attendance', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Module')),
            ],
        ),
    ]
