# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
